src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Geo__c</fullName>
        <description>Account Geo field configured for demo . A decision will be taken on approach to be used to select country, Geo , region and match it with On premises. This is a temporary field (may be deleted)</description>
        <label>Account Geo</label>
        <picklist>
            <controllingField>Account_Country__c</controllingField>
            <picklistValues>
                <fullName>ASMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IJKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Account_Sub_Geo__c</fullName>
        <label>Account Sub Geo</label>
        <picklist>
            <picklistValues>
                <fullName>ASMO 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA 1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/SMG_Country_State_Reference__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>SMG_Geo__c</fullName>
        <label>Geo</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMG_Sub_Geo__c</fullName>
        <label>Sub Geo</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Country State Reference</label>
</CustomObject>

src/classes/Core_Account_Handler.cls
public class Core_Account_Handler{

    public static void AccountBeforeHandler(List<Account> listNewAcccount,Map<Id,Account> mapNewAccount,Map<Id,Account> mapOldAccount){
        
        Map<String,SMG_Country_State_Reference__c> cSCountryStateRef = SMG_Country_State_Reference__c.getall();
        for(Account sobjAccount : listNewAcccount){
            if(mapNewAccount == NULL || sobjAccount.BillingState != mapOldAccount.get(sobjAccount.Id).BillingState){
                if(cSCountryStateRef.containsKey(sobjAccount.BillingState)){
                    sobjAccount.Account_Geo__c= cSCountryStateRef.get(sobjAccount.BillingState).SMG_Geo__c;
                    sobjAccount.Account_Sub_Geo__c = cSCountryStateRef.get(sobjAccount.BillingState).SMG_Sub_Geo__c;  
                }
                else{
                    sobjAccount.Account_Geo__c= NULL;
                    sobjAccount.Account_Sub_Geo__c = NULL; 
                }
            }
        }
    }
}