src/objects/Capability_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>CCV__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCV__c</fullName>
        <label>CCV</label>
        <referenceTo>CCV__c</referenceTo>
        <relationshipLabel>Capability Matrix</relationshipLabel>
        <relationshipName>Capability_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <label>Other</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>People__c</fullName>
        <label>People</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services__c</fullName>
        <label>Products / Services</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Programs__c</fullName>
        <label>Programs</label>
        <type>TextArea</type>
    </fields>
    <label>Capability Matrix</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Capability Matrix</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capability Matrix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CCV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CCV</relationshipLabel>
        <relationshipName>CCV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>CCV</relationshipLabel>
        <relationshipName>CCV</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CCV</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CCV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Value_Chain__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>CCV__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCV__c</fullName>
        <label>CCV</label>
        <referenceTo>CCV__c</referenceTo>
        <relationshipLabel>Value Chain</relationshipLabel>
        <relationshipName>Value_Chain</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Challenges__c</fullName>
        <label>Challenges</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <picklist>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Goals__c</fullName>
        <label>Wider Goals</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <label>KPI</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Proposals__c</fullName>
        <label>Intel Value Proposal</label>
        <type>TextArea</type>
    </fields>
    <label>Value Chain</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Value Chain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Chain</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Core_CCV_CloneController.cls
public class Core_CCV_CloneController {

    //added an instance varaible for the standard controller
    private ApexPages.StandardController controller {get; set;}
    
     // add the instance for the variables being passed by id on the url
    private CCV__c ccv {get;set;}
    
    // set the id of the record that is created -- ONLY USED BY THE TEST CLASS
    public ID newRecordId {get;set;}

    // initialize the controller
    public Core_CCV_CloneController(ApexPages.StandardController controller) {

        //initialize the stanrdard controller
        this.controller = controller;
        
        // load the current record
        ccv = (CCV__c)controller.getRecord();

    }

    // method called from the VF's action attribute to clone the CCV
    public PageReference cloneWithItems() {

         // setup the save point for rollback
         Savepoint sp = Database.setSavepoint();
         CCV__c newCCV;

         try {

             ccv = [select Id, Name, Account__c, Opportunity__c from CCV__c where id = :ccv.id];
             newCCV = ccv.clone(false);
             insert newCCV;

             // set the id of the new po created for testing
             newRecordId = newCCV.id;

             List<Value_Chain__c> itemsVC = new List<Value_Chain__c>();
             for (Value_Chain__c vc : [SELECT Id, Name, CCV__c, Challenges__c, Function__c, Proposals__c, KPI__c, Goals__c FROM Value_Chain__c WHERE CCV__c = :ccv.id]) {
                  Value_Chain__c newVC = vc.clone(false);
                  newVC.CCV__c = newCCV.id;
                  itemsVC.add(newVC);
             }
             insert itemsVC;

             List<Capability_Matrix__c> itemsCM = new List<Capability_Matrix__c>();
             for (Capability_Matrix__c cm : [SELECT Id, Name, CCV__c, Company__c, Other__c, People__c, Products_Services__c, Programs__c FROM Capability_Matrix__c WHERE CCV__c = :ccv.id]) {
                  Capability_Matrix__c newCM = cm.clone(false);
                  newCM.CCV__c = newCCV.id;
                  itemsCM.add(newCM);
             }
             insert itemsCM;             
             
         } catch (Exception e){
             // roll everything back in case of error
            Database.rollback(sp);
            ApexPages.addMessages(e);
            return null;
         }

        return new PageReference('/'+newCCV.id+'/e?retURL=%2F'+newCCV.id);
    }

}