src/objects/CCV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CCV</relationshipLabel>
        <relationshipName>CCV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>CCV</relationshipLabel>
        <relationshipName>CCV</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CCV</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CCV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Value_Chain__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>CCV__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCV__c</fullName>
        <label>CCV</label>
        <referenceTo>CCV__c</referenceTo>
        <relationshipLabel>Value Chain</relationshipLabel>
        <relationshipName>Value_Chain</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Challenges__c</fullName>
        <label>Challenges</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <picklist>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Goals__c</fullName>
        <label>Wider Goals</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <label>KPI</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Proposals__c</fullName>
        <label>Intel Value Proposal</label>
        <type>TextArea</type>
    </fields>
    <label>Value Chain</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Value Chain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Chain</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Core_CCV_Controller.cls
public with sharing class Core_CCV_Controller {

    public CCV__c ccvRec { get; set; }
    public List<Value_Chain__c> ccvDetail { get; set; }

    public Core_CCV_Controller() {
    
        String paramId = apexpages.currentpage().getparameters().get('id');
           
        ccvRec = [SELECT Id, Name, Account__c, Opportunity__c 
                  FROM CCV__c 
                  WHERE Id = :paramId];

        ccvDetail = [SELECT Id, Function__c, KPI__c, Challenges__c, Goals__c, Proposals__c
                     FROM Value_Chain__c 
                     WHERE CCV__c = :paramId
                     ORDER BY Function__c];

        while (ccvDetail.size() <= 4)
        {
            ccvDetail.add(ccvDetail[0]);
        }
    }

}