src/objects/Change_Requests__c.object
<CustomObject>
    <description>Form to request changes to Account data/MDM</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Request</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Change Requests</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Core_Change_Request_Handler.cls
/**************************************************************************************
Apex Class Name:  Core_Change_Request_Handler
Version     : 1.0 
Created Date: 30 SEP 2014
Function    : Handler Class for trigger on Change Request object
Modification Log :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Harshith M L             30/09/2014              Original Version
*************************************************************************************/
public class Core_Change_Request_Handler
{
    /*
    * Method name  : ChangeRequestBeforeHandler
    * Description  : Method to update the owner of Change Request record to the related account owner on creation/updation. 
    * Return Type  : VOID
    * Parameter    : List Trigger.new, MAP Trigger.newmap
    */
    
    public static void ChangeRequestBeforeHandler(List<Change_Requests__c> changeRequestList,Map<Id,Change_Requests__c> changeRequestMap)
    {
        Map<Id,Account> accountMap;
        Set<Id> accountIds = new Set<Id>();
        
        for(Change_Requests__c changeRequestInstance : changeRequestList)
        {
            accountIds.add(changeRequestInstance.Account__c);
        }
        
        accountMap = new Map<Id,Account>([SELECT Id,OwnerId FROM Account Where Id In :accountIds]);
        
        for(Change_Requests__c changeRequestInstance : changeRequestList)
        {
            changeRequestInstance.OwnerId = accountMap.get(changeRequestInstance.Account__c).OwnerId;
        }
    }
}