src/objects/Change_Requests__c.object
<CustomObject>
    <description>Form to request changes to Account data/MDM</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Request</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Change Requests</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Core_Change_Request_Handler_Test.cls
/****************************************************************************************************
Apex Class Name:  Core_Change_Request_Handler_Test
Version     : 1.0 
Created Date: 06 OCT 2014
Function    : Test class for "Core_ChangeRequest" Trigger and "Core_Change_Request_Handler" Class
Modification Log :
* Developer                   Date                   Description
* ----------------------------------------------------------------------------                 
* Harshith M L             06/10/2014              Original Version
*****************************************************************************************************/

@isTest 
private class Core_Change_Request_Handler_Test
{
    Static List<Account> accountList;
    
    Static List<Change_Requests__c> changeRequestList;
    
    Static user systemAdminUser;
    
    
    /*
    * Method name  : setupTestData
    * Description  : Method to setup test data ( Accounts )
    * Return Type  : None
    * Parameter    : None
    */
    
    static void setupTestData()
    {
        List<User> usersList = new List<User>();
        usersList = [SELECT Id,Name FROM User where isActive = TRUE AND Profile.Name = 'System Administrator'];
        
        for(User sysAdminUser : usersList)
        {
            if(sysAdminUser.Id != UserInfo.getUserId())
                systemAdminUser = sysAdminUser;
        }
        
        accountList = new List<Account>();
        accountList = Core_Utility_data_create.createAccount(20);
        insert accountList;

    }
    
    /*
    * Method name  : setupChangeRequest
    * Description  : Method to setup test data ( Change Request)
    * Return Type  : None
    * Parameter    : None
    */
    
    static void setupChangeRequest()
    {
       changeRequestList = new List<Change_Requests__c >();
       changeRequestList = Core_Utility_data_create.createChangeRequest(accountList);
       insert changeRequestList;

    }
    
    
    /*
    * Method name  : changeRequestCreate
    * Description  : Testmethod method for testing "Core_ChangeRequest" Trigger and "Core_Change_Request_Handler" Class
    * Return Type  : None
    * Parameter    : None
    */
   
    static testMethod void changeRequestCreate() 
    {
        setupTestData();
        
        Test.startTest();
        
        System.runAs(systemAdminUser)
        {
            setupChangeRequest();
        }
        
        for(Change_Requests__c changeRequestInstance : changeRequestList)
            System.assertEquals(changeRequestInstance.OwnerId, changeRequestInstance.Account__r.OwnerId);
            
        Test.stopTest();
        
        
    }
    
}